"""Convert the Markdown manuscript into a Q1-formatted Word document.

The script parses the manuscript and constructs a DOCX with Times New Roman
body text, bold headings, properly formatted tables, equations and the 15
figures generated by the experimental pipeline.
"""
from __future__ import annotations

import re
from pathlib import Path

from docx import Document
from docx.enum.table import WD_ALIGN_VERTICAL, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Cm, Inches, Pt, RGBColor

ROOT = Path(__file__).resolve().parent.parent
MS_PATH = ROOT / "manuscript" / "manuscript.md"
OUT_PATH = ROOT / "manuscript" / "Article_Online_Examination_Q1.docx"
FIG_DIR = ROOT / "figures"

# Mapping of insertion points (line content prefix) to figures
FIGURE_INSERTIONS = {
    "### 3.2 Pipeline Overview": [("fig_architecture.png", "Figure 1. End-to-end privacy-preserving proctoring pipeline.")],
    "### 4.4 Data-Flow": [("fig_si_timeline.png", "Figure 2. Simulated 60-second session illustrating the trajectory of the visual, acoustic and behavioural risk components and the resulting Suspicion Index.")],
    "Mean per-image inference latency on the COCO subset": [
        ("fig_visual_pr_curves.png", "Figure 3. Precision-recall curves of YOLOv8-s on the COCO val2017 proctoring subset (217 images, 1,164 annotations)."),
        ("fig_visual_tp_fp.png", "Figure 4. Per-class true-positive and false-positive counts after greedy IoU 0.5 matching."),
    ],
    "Mean per-buffer inference latency": [
        ("fig_acoustic_roc_pr.png", "Figure 5. ROC and PR curves for the Whisper-Base content-free acoustic module on the LibriSpeech-derived benchmark."),
        ("fig_acoustic_per_class.png", "Figure 6. Per-class distribution of the secondary-speaker probability on the 400-clip acoustic benchmark."),
    ],
    "Off-screen gaze is detected reliably": [
        ("fig_behaviour_distributions.png", "Figure 7. Per-scenario distribution of the geometric descriptors (yaw amplitude and lip variance) computed from MediaPipe FaceMesh landmarks of real Pexels face anchors."),
    ],
    "Visual cues dominate the decision": [
        ("fig_fusion_comparison.png", "Figure 8. Cross-validated F1 of the five fusion strategies on real-modality features (error bars = standard deviation over 5 folds)."),
        ("fig_fusion_roc.png", "Figure 9. ROC curves of all fusion strategies pooled across the 5 cross-validation folds."),
        ("fig_fusion_confusion.png", "Figure 10. Confusion matrix of the random-forest fusion model under 5-fold cross-validation on real features."),
        ("fig_fusion_ablation.png", "Figure 11. Leave-one-modality-out and only-one-modality ablation results."),
    ],
    "Peak resident memory is 1,075 MB": [
        ("fig_latency.png", "Figure 12. Per-module inference latency on the Apple M4 Max host (Mac Studio, 14-core CPU, 32-core integrated GPU, 36 GB unified memory) with both MPS GPU acceleration and CPU-only configurations."),
    ],
    "The recommended operating envelope is therefore": [
        ("fig_robustness.png", "Figure 13. Robustness study: class-presence recall versus gamma and scale for the visual subsystem, and F1 plus score distributions versus SNR for the acoustic subsystem under real LibriSpeech noise injection."),
    ],
    "This is, to the best of our knowledge, the strongest empirical": [
        ("fig_privacy.png", "Figure 14. Adversarial privacy verification on 30 real LibriSpeech speakers: re-identification AUC achieved by a raw-audio attacker (proxy of conventional proctoring) versus a metadata-only attacker (the proposed system)."),
    ],
    "## 7. Discussion": [
        ("fig_summary_table.png", "Figure 15. Aggregate summary of the empirical performance, latency and privacy metrics of the proposed framework."),
    ],
}


def set_run_default(run, size: float = 11, bold: bool = False, italic: bool = False, font: str = "Times New Roman"):
    run.font.name = font
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    r = run._element
    rpr = r.get_or_add_rPr()
    rFonts = rpr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = OxmlElement("w:rFonts")
        rpr.insert(0, rFonts)
    rFonts.set(qn("w:ascii"), font)
    rFonts.set(qn("w:hAnsi"), font)
    rFonts.set(qn("w:cs"), font)


def add_heading_styled(doc, text: str, level: int = 1):
    if level == 0:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(text)
        set_run_default(run, size=16, bold=True)
        return p
    sizes = {1: 14, 2: 12, 3: 11, 4: 11}
    p = doc.add_paragraph()
    run = p.add_run(text)
    set_run_default(run, size=sizes.get(level, 11), bold=True)
    p.paragraph_format.space_before = Pt(8)
    p.paragraph_format.space_after = Pt(4)
    return p


def add_paragraph_text(doc, text: str, *, italic: bool = False, alignment=None):
    """Add a paragraph with mixed bold/italic via simple markdown parsing."""
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.line_spacing = 1.2
    if alignment:
        p.alignment = alignment
    parts = re.split(r"(\*\*[^*]+\*\*|\*[^*]+\*)", text)
    for part in parts:
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            r = p.add_run(part[2:-2])
            set_run_default(r, bold=True, italic=italic)
        elif part.startswith("*") and part.endswith("*"):
            r = p.add_run(part[1:-1])
            set_run_default(r, italic=True)
        else:
            r = p.add_run(part)
            set_run_default(r, italic=italic)
    return p


def add_authors_block(doc):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run("Radid Ali, Ghazouani Mohamed, El habib Benlahmar")
    set_run_default(r, size=12, bold=True)
    p2 = doc.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r2 = p2.add_run(
        "Department of Mathematics and Computer Science, Hassan II University, Faculty of Sciences Ben M'sik, Casablanca, Morocco"
    )
    set_run_default(r2, size=10, italic=True)
    p3 = doc.add_paragraph()
    p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r3 = p3.add_run("radidalix@outlook.fr, ghazouani.fsbm@gmail.com, h.benlahmer@gmail.com")
    set_run_default(r3, size=10)


def add_table_from_md(doc, header: list[str], rows: list[list[str]]):
    """Render a markdown-style table as a DOCX table."""
    table = doc.add_table(rows=1 + len(rows), cols=len(header))
    table.style = "Light Grid Accent 1"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    for j, h in enumerate(header):
        cell = table.rows[0].cells[j]
        cell.text = ""
        p = cell.paragraphs[0]
        r = p.add_run(h)
        set_run_default(r, size=10, bold=True)
        cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
    for i, row in enumerate(rows, start=1):
        for j, val in enumerate(row):
            cell = table.rows[i].cells[j]
            cell.text = ""
            p = cell.paragraphs[0]
            text = val.strip()
            is_bold = text.startswith("**") and text.endswith("**")
            if is_bold:
                text = text[2:-2]
            r = p.add_run(text)
            set_run_default(r, size=10, bold=is_bold)
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(8)


def add_figure(doc, fig_name: str, caption: str, width_inches: float = 6.0):
    fig_path = FIG_DIR / fig_name
    if not fig_path.exists():
        print(f"  WARN: missing {fig_path}")
        return
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run()
    run.add_picture(str(fig_path), width=Inches(width_inches))
    cap = doc.add_paragraph()
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cap.paragraph_format.space_after = Pt(10)
    r = cap.add_run(caption)
    set_run_default(r, size=9, italic=True)


def parse_table(lines: list[str], start_idx: int) -> tuple[list[str], list[list[str]], int]:
    """Parse a markdown table starting at start_idx (header line). Return header, rows, next_idx."""
    header_line = lines[start_idx]
    sep_line = lines[start_idx + 1]
    if not re.match(r"\s*\|.*\|\s*$", sep_line):
        return None
    header = [c.strip() for c in header_line.strip().strip("|").split("|")]
    rows = []
    i = start_idx + 2
    while i < len(lines):
        ln = lines[i]
        if not re.match(r"\s*\|.*\|\s*$", ln):
            break
        rows.append([c.strip() for c in ln.strip().strip("|").split("|")])
        i += 1
    return header, rows, i


def render():
    doc = Document()

    # Set default page margins
    for section in doc.sections:
        section.top_margin = Cm(2.0)
        section.bottom_margin = Cm(2.0)
        section.left_margin = Cm(2.0)
        section.right_margin = Cm(2.0)

    # Set the default style font
    style = doc.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(11)

    md_text = MS_PATH.read_text()
    lines = md_text.splitlines()

    title_added = False
    i = 0
    in_meta = False

    while i < len(lines):
        line = lines[i]

        # Check for figure insertion points (line contains trigger string)
        for trigger, figs in FIGURE_INSERTIONS.items():
            if line.startswith(trigger):
                # Process trigger line first (heading / paragraph)
                break

        if line.startswith("# "):
            if not title_added:
                add_heading_styled(doc, line[2:].strip(), level=0)
                title_added = True
            else:
                add_heading_styled(doc, line[2:].strip(), level=1)
            i += 1
            continue
        if line.startswith("## "):
            add_heading_styled(doc, line[3:].strip(), level=1)
            # Insert figure after this heading if matched
            for trigger, figs in FIGURE_INSERTIONS.items():
                if trigger in line:
                    for f, cap in figs:
                        add_figure(doc, f, cap)
            i += 1
            continue
        if line.startswith("### "):
            add_heading_styled(doc, line[4:].strip(), level=2)
            for trigger, figs in FIGURE_INSERTIONS.items():
                if trigger in line:
                    for f, cap in figs:
                        add_figure(doc, f, cap)
            i += 1
            continue
        if line.startswith("#### "):
            add_heading_styled(doc, line[5:].strip(), level=3)
            i += 1
            continue
        if line.strip().startswith("**Radid Ali**"):
            add_authors_block(doc)
            # Skip until the abstract line
            j = i + 1
            while j < len(lines) and not lines[j].strip().startswith("**Abstract**") and not lines[j].startswith("## "):
                j += 1
            i = j
            continue
        if line.strip().startswith("**Abstract**"):
            p = doc.add_paragraph()
            r = p.add_run("Abstract — ")
            set_run_default(r, size=11, bold=True)
            rest = line.strip()[len("**Abstract**"):].lstrip(" :—-")
            r2 = p.add_run(rest)
            set_run_default(r2, size=11)
            p.paragraph_format.space_after = Pt(6)
            i += 1
            continue
        if line.strip().startswith("**Keywords**"):
            p = doc.add_paragraph()
            r = p.add_run("Keywords — ")
            set_run_default(r, size=11, bold=True, italic=True)
            rest = line.strip()[len("**Keywords**"):].lstrip(" :—-")
            r2 = p.add_run(rest)
            set_run_default(r2, size=11, italic=True)
            p.paragraph_format.space_after = Pt(6)
            i += 1
            continue
        # Table detection
        if re.match(r"\s*\|.*\|\s*$", line):
            parsed = parse_table(lines, i)
            if parsed:
                header, rows, next_i = parsed
                add_table_from_md(doc, header, rows)
                i = next_i
                continue
        # Code blocks
        if line.strip().startswith("```"):
            j = i + 1
            while j < len(lines) and not lines[j].strip().startswith("```"):
                j += 1
            block_text = "\n".join(lines[i + 1 : j])
            p = doc.add_paragraph()
            r = p.add_run(block_text)
            set_run_default(r, size=9, font="Courier New")
            p.paragraph_format.space_after = Pt(6)
            i = j + 1
            continue
        # Equations (LaTeX-style $$...$$)
        if line.strip().startswith("$$") and line.strip().endswith("$$") and len(line.strip()) > 4:
            content = line.strip()[2:-2].strip()
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            r = p.add_run(content)
            set_run_default(r, size=11, italic=True)
            i += 1
            continue
        if line.strip().startswith("$$"):
            j = i + 1
            block = []
            while j < len(lines) and not lines[j].strip().startswith("$$"):
                block.append(lines[j])
                j += 1
            content = " ".join(block)
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            r = p.add_run(content.strip())
            set_run_default(r, size=11, italic=True)
            i = j + 1
            continue
        # Bulleted/numbered lists
        if line.strip().startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            text = line.strip()[2:]
            parts = re.split(r"(\*\*[^*]+\*\*|\*[^*]+\*)", text)
            for part in parts:
                if not part:
                    continue
                bold = part.startswith("**") and part.endswith("**")
                italic = part.startswith("*") and part.endswith("*") and not bold
                clean = part.strip("*")
                r = p.add_run(clean)
                set_run_default(r, bold=bold, italic=italic)
            i += 1
            continue
        m_num = re.match(r"^(\d+)\.\s+(.*)", line.strip())
        if m_num:
            p = doc.add_paragraph(style="List Number")
            text = m_num.group(2)
            parts = re.split(r"(\*\*[^*]+\*\*|\*[^*]+\*)", text)
            for part in parts:
                if not part:
                    continue
                bold = part.startswith("**") and part.endswith("**")
                italic = part.startswith("*") and part.endswith("*") and not bold
                clean = part.strip("*")
                r = p.add_run(clean)
                set_run_default(r, bold=bold, italic=italic)
            i += 1
            continue
        # Plain paragraphs - join consecutive non-empty lines
        if line.strip() == "":
            i += 1
            continue
        # Accumulate until blank line
        para_lines = [line]
        j = i + 1
        while j < len(lines) and lines[j].strip() != "" and not lines[j].startswith(("#", "|", "- ", "$$", "```")) and not re.match(r"^\d+\.\s", lines[j].strip()):
            para_lines.append(lines[j])
            j += 1
        full = " ".join(p.strip() for p in para_lines)
        add_paragraph_text(doc, full)
        # Insert figure after paragraph if it contains a trigger
        for trigger, figs in FIGURE_INSERTIONS.items():
            if trigger in full and not trigger.startswith("##") and not trigger.startswith("###"):
                for f, cap in figs:
                    add_figure(doc, f, cap)
        i = j

    doc.save(OUT_PATH)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    render()
